---
language: csharp

mono:
  - 4.6.1
  - 4.8.1
  - weekly
  - latest

before_install:
  - rvm install 2.2.3

install:
  - gem install bundler
  - bundle

before_script:
  - echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" >> /etc/apt/sources.list
  - wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
  - sudo apt-get -qq update
  - sudo apt-get install -y libzmq3-dev

script:
  - bundle exec rake DEBUG=true

matrix:
  allow_failures:
   - mono: latest
   - mono: weekly
   - mono: 4.4.2

env:
  global:
    - TMPDIR=/tmp
